env:
  global:
  - REPO=startx/monkey-ops
  - CGO_ENABLED=0
  - GOOS=linux
  - secure: ke0XMZsmf+GBT2TpP6SHmxk8ZrST5mfyp9SRpBgjvF6fgsFKqi/wW+5aS+HNvgo63nDFb1OmHzhNfnK5AnD2T1nfb1iyrXT3cdfDJBsvg7elValG8vFLuLt3gITMwO0yj+tVqEVyvsfOLgSRPuu2Tm6mHCPpdJroQy3eU171OhLEUQv4dXNSg892tvEfnrOpdsVjHas9AeSrCgdT+FES9dk6Rve4AxBQS8ptxDzM6iEQUMDxIXTfIDw/3knPC4yJPKoKYlPrw187f8mGAraWdgzmSGWBvY+mQIh0V5L6uVbD0ykBvZf/ccojQUTu6rzPdV2zrtPzxRamSRiXstcxuazD4VLMJv6MfnJYUxQMM2KoqHKDcp2xyoX5J1bR26bdv/Mm2EEvCFzQmW6opZumSwj2LXJi3teGUzBQuDEvUYqpzoxNSzapXwCCIw9ad9JjbP6aZ5wITsnfYj7R9VLvKOUEmzLPyIdIycE0JgDxy9s0xUVjR4sXjDWWtPv+ULUEJV4awbZPdmtlznVz9yuH6SO4O837/hFKIwFxs6yDVsE3jFnhQWLG3tYP9KVzf2BSeO/8kgUAKI0CJoGf6dUUZUvTNt6S5Lr5Updl8HH4k1J9Q09ml91b6XeqMKc6m0Ztf06y3D2ygT3WSfHIqO+A7mEau6FetLOv4m+Wt2f6In4=
  - secure: nt9tOWun5WktCF1c04xLSs512NS7YWRPFR5fljEEnj1H13N8z8bvdgitDWP1DUCz+QKEbqz/+KcwfYRLnErg/inpdMnsfwkYFJvr+TlHM7oPH/2Lp/9odLRrW5KO3mHlJVK+ojF1Oa2hgFxkB27AKPJwl5rTQdJXAOgS+4/VbVlhYVCuLhntKrVGvAlwQWjGijQZmz1Y36pjFZN1lj8UDFAwXOfzDWSgdHv5z/tfi+eszGTO5iuXPElFLhfX93RT/9SGj3MFDbCiIA+nQ8wgDGqYdB5ttDPxXJX+LS4YR3TGlB9xTbedM+m+1H7bzijjbOu3Iont9pyJf6hD7sabDHTwNvOjgQL4DMve6zEXt/NNEMOanGZlgQJSrOIn1HLJdOxr7s3EYlRALGyEM+VSQ/DooMhiWpgQJ0kpT15uk9I5DcQc5NE+bKJO1KrM/IBmNSjRE56GrTtTiQrodhRsNFdwtcZYd2yD3sSbKiHEWPLyMjWw7vP7nE6WTIHE5jAugb6B/db7sYERskv4ISGwsFChMKMTgJ+lAKEnrxZRJOXsmpvESZUQHM8EZgDe+I8pyjCBp0ajsULs+fwiVaalyWXZ0YVzPS77We8EdYFt5ptqWTX+Ui714BmUXrhRvy2vsN/j12oFwLsySUGXxOQG1Wis6JvwQpc2sdSvY455VTY=
sudo: required
services:
- docker
language: go
before_install:
- 'echo "{ \"experimental\": true, \"storage-driver\": \"overlay2\", \"max-concurrent-downloads\":50,\"max-concurrent-uploads\":
  50 }" | sudo tee /etc/docker/daemon.json'
- sudo service docker restart
- docker images
- mkdir ~/.gocache
- export GOPATH=~/.gocache
- go get -v -u github.com/spf13/viper
- go get -v -u github.com/spf13/pflag
- go get -v -u github.com/gorilla/mux
- go build -a -installsuffix cgo -o ./image/monkey-ops ./go/*.go
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; elif [ "$TRAVIS_BRANCH"  ==
  "test" ]; then echo "testing"; else echo $TRAVIS_BRANCH ; fi`
script:
- cd ./image
- docker build --squash -t $REPO:$TAG .
- docker run -d --name monkey-test $REPO:$TAG --TOKEN=token
after_success:
- docker push $REPO:$TAG
